### ISSUE TITLE
Sample - Graphics - AnimatedModel.sln

### ISSUE THREAD

**Issue by dud3** [SiliconStudio/xenko-samples#1] opened 2016-02-13 17:46 UTC
Sample doesn't seem to be working, at least on my computer.

Debug info:
![001](https://cloud.githubusercontent.com/assets/5823644/13029075/0fee604c-d282-11e5-8309-54ae612dec0f.png)

**Comment by dud3** [comment] 2016-02-13 17:57
Wrong repo, but this one seems to be a sample from 1.5.2-beta.

**Comment by dud3** [comment] 2016-02-13 18:02
Actually it seems to be here. :)

**Comment by xenux** [comment] 2016-02-15 10:26
Hi dud!

Thank you for the report. 
I have one question: did you make any modifications to the sample before having the crash (such as modifying the materials, etc) ? The problem is that the shader created is too heavy for the targeted graphic profile (9_1). It is not supposed to happened with the sample as it is provided though. 
Note that we will add better support for low profiles soon. In the mean time, if you just want play with the sample you can simply increase the graphic profile to 10 or 11 in the game settings to solve the problem.

**Comment by dud3** [comment] 2016-02-16 09:31
Hi @xenux 

I've tried the clean version of the sample from the beginning again, but unfortunately got the same error. ;(

I'll try your suggestion. One silly question: Where would the `game settings` be, in the source code of the sample, or in the game engine itself, or perhaps both?

Thanks.

**Comment by xenux** [comment] 2016-02-17 06:16
Thank you for the clarifications, we will investigate the problem.

Concerning the Game Settings, you can find them in the asset view and edit them from the property grid.

**Comment by jwollen** [comment] 2016-02-19 01:25
Hi!
Could you send us/post here the shader log file generated by the sample?
It should be the newest *.hlsl file in "AnimatedModel\Bin\Windows\Debug\log".
Thanks in advance!

**Comment by dud3** [comment] 2016-02-25 15:04
@jwollen Sorry, for my late reply, I'll do that today. :)

**Comment by dud3** [comment] 2016-02-25 20:03
Github didn't allow me to upload this files, but I've posted them in the following links:

http://pastebin.com/12ndCLhT
http://pastebin.com/jdNsqDLK

**Comment by xenux** [comment] 2016-03-03 11:31
This should be fixed in last release now! 
Thank you for the report :)

**Closed by xenux** 2016-03-03 11:31 UTC
